select * from Addresses
select * from Billing
select * from CostInformation
select * from DepartmentInformation
select * from DiagnosticsDetails
select * from DischargeInformation
select * from EmployeeHistory
select * from EmployeeInformation
select * from GeneralHistory
select * from HospitalInfrastructure
select * from HospitalizationInformation
select * from HospitalRates

select * from Insurance
select * from InsuranceCompanies
select * from PatientHealthHistory
select * from PatientInformation
select * from PatientRoom
select * from PatientVisitor
select * from Payroll
select * from PersonInformation
select * from Phone
select * from PhysicianDetails
select * from RefferedbyDoctorDetails
select * from TreatmentDeatils
select * from VisitorInformation
